### ISSUE TITLE
Campo de anexo não recebe imagem nenhuma

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#1]
O campo está incapaz de receber imagem, sempre dizendo para colocar um anexo que seja válido.
https://drive.google.com/file/d/1NofuyH0H6KnzZOLhbxHRseUubjllnuai/view?usp=sharing

**Comment by lsena-web** [comment]
em qual formulário?

**Comment by lsena-web** [comment]
bug corrigido
