### ISSUE TITLE
Não alerta campo vazio

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#14]
Ao deixar o campo "Descrição" vazio e tentar salvar o cadastro de aluno, o sistema nem completa e nem avisa que está vazio. O mesmo ocorre na adição de exercícios		
https://drive.google.com/file/d/1eqhbXxh7q8u5p61mUprx6sSkRJVukjj1/view?usp=sharing

**Comment by lsena-web** [comment]
devido a dificuldade e possíveis problemas na correção do erro, foi conversado e decidido que a melhor solução seria tornar a descrição opcional
