### ISSUE TITLE
Campo de Descrição

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#2]
Ao deixar o campo "Descrição" vazio e tentar salvar o cadastro, o sistema nem completa e nem avisa que está vazio.
https://drive.google.com/file/d/1eqhbXxh7q8u5p61mUprx6sSkRJVukjj1/view?usp=sharing

**Comment by lsena-web** [comment]
em qual formulário?

**Comment by lsena-web** [comment]
em qual formulário?
