### ISSUE TITLE
Emails repetidos

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#3]
O sistema permite que alunos sejam cadastrados com emails do usuário principal, bem como o usuário principal editar o email para um usado por um aluno (cadastrado).
https://drive.google.com/file/d/1r30ffqhvoO8zkby46q_MlHqenNmOxNNG/view?usp=sharing

**Comment by lsena-web** [comment]
solucionado

**Comment by LuanLima12** [comment]
Persistiu
https://drive.google.com/file/d/1iF__RUceDROUduq_cs8ObzR8cAEbnEHk/view?usp=sharing

**Comment by lsena-web** [comment]
corrigido!
