### ISSUE TITLE
Problemas com arquivos

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#5]
O sistema não aceita arquivos TXT, DOC ou PDF na criação ou alteração de um exercício
https://drive.google.com/file/d/10MuXLcYNdOikksNNoS4Xsuc5aAdZVL5-/view?usp=sharing

**Comment by lsena-web** [comment]
o exercício está apto apenas para as seguintes extensões: "png", "jpge", "jpg", "svg", "mp4", "mkv", "avi", "wmv", "wma", "rmvb", "mov", "3gp", "flv", "gif"
