### ISSUE TITLE
Avaliações e horários permanecem após exclusão do aluno

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#6]
O sistema não exclui avaliações ou horários de exercícios vínculados ao aluno, no banco.
https://drive.google.com/file/d/13t95yHhIvYPtQcJrFwTEvOHZuKoWERWd/view?usp=sharing

**Comment by lsena-web** [comment]
em desenvolvimento

**Comment by lsena-web** [comment]
corrigido!
