### ISSUE TITLE
Data de exercício que inicia no futuro e termina no passado

### ISSUE THREAD

**Issue by LuanLima12** [lsena-web/ricefit#9]
Erro: O sistema perde a data de fim e, nesse mesmo caso, ele não consegue realizar o delete deste agendamento de horário

https://drive.google.com/file/d/11rOYMw3eFXVRKBEYLuOraFitWsTlwASA/view?usp=sharing
https://drive.google.com/file/d/1LIK9rAJPjzhdrcpp7Ni4QiBNAVzRCfvJ/view?usp=sharing

**Comment by lsena-web** [comment]
corrigido!
